# Generated by Django 4.2.4 on 2023-08-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='blog',
            new_name='post',
        ),
    ]
